### PR TITLE
Support SampleSet for `initial_states`

### LINKED ISSUE #53: Accept SampleSet for initial_states
Since `neal.SimulatedAnnealingSampler.sample` is returning a `dimod.SampleSet`, it should also be able to accept it for `initial_states` parameter (instead of ndarray + labels map).

### PR DESCRIPTION
**Pull request by randomir**
Deprecate the old tuple format.

Close #53.

### CODE REVIEW

**Comment by randomir** [comment]
This is a minor, backwards-compatible, PR, so I'll just go ahead and merge it in.

But, how do you feel about **deprecation** of the `tuple` format for `initial_states`, @arcondello, @wbernoudy?

**Comment by wbernoudy** [comment]
Could we use dimod's concept of [samples_like](https://docs.ocean.dwavesys.com/projects/dimod/en/latest/reference/generated/dimod.as_samples.html#dimod.as_samples)? Otherwise, I'm fine with deprecation of the tuple format and just using `SampleSet`.

**Comment by randomir** [comment]
@wbernoudy, the "samples_like" support sounds good (and note that `dimod.as_samples()` returns the samples/labels tuple we're deprecating), but it doesn't solve the problem of stating the vartype of the samples.

`SampleSet` includes everything `as_samples` returns + vartype + energies.

Energies are spam here, but at least conversion is simple:
```
initial_states = dimod.SampleSet(samples_like, 'SPIN', 0)
```

**Comment by randomir** [comment]
On a related note, I've been advocating for null energies in `SampleSet`, by default. But we still haven't gotten to an agreement there. /cc @arcondello.

**Comment by arcondello** [comment]
We can infer the vartype from the samples, and in the ambiguous (all-1s) case we could assume it matches the BQM.

**Pull request merged**
